name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarQubeScan:
    name: SonarQube Scan
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: '.' # lub np. ./backend jeśli tam jest kod
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
